### ISSUE TITLE
Frontend - Change all occurrences of any into a suitable type.

### ISSUE THREAD

**Issue by joffe97** [capgemini-stavanger/gi-en-jul#193] opened 2021-07-08 12:38 UTC
There shouldn't be any usage of the `any` type. Change to a suitable type, or `unknown` if the type really is unknown.

**Comment by TheseusDeus** [comment] 2021-07-28 12:29
This issue should be way more specific. Like the actual files or just close the issue

**Comment by Sommerli** [comment] 2021-08-02 11:02
Closing as the issue is unspecific and somewhat solved with refactoring that has been done

**Closed by Sommerli** 2021-08-02 11:02 UTC
Labels: Technical
