### ISSUE TITLE
Nav bar too low in giver page

### ISSUE THREAD

**Issue by HGodal** [capgemini-stavanger/gi-en-jul#475] opened 2021-09-30 06:24 UTC
**Describe the bug**
The nav menu on the giver page "familiesammensetning" is too far down, introducing scrolling.

**Expected behavior**
The nav bar location should be consistent across all registration pages.

**Comment by Sommerli** [comment] 2021-11-17 10:28
Duplicate of #450

**Closed by Sommerli** 2021-11-17 10:28 UTC
